// SNF (Skilled Nursing Facility) Chart of Accounts
// Comprehensive account structure for P&L analysis with PPD metrics

import { COAAccount, PPDBenchmark } from './types';

export const SNF_CHART_OF_ACCOUNTS: COAAccount[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // REVENUE - 4000 Series
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: '4000',
    name: 'Revenue',
    category: 'revenue',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },

  // Non-Skilled Revenue - 4100 Series
  {
    code: '4100',
    name: 'Non-Skilled Revenue',
    category: 'revenue',
    subcategory: 'non_skilled',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '4110',
    name: 'Medicaid Revenue',
    shortName: 'Medicaid',
    category: 'revenue',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'non_skilled_days',
    formatType: 'currency',
    mappingKeys: ['medicaid_revenue', 'medicaid_daily_rate', 'mcaid_rev'],
  },
  {
    code: '4120',
    name: 'Managed Medicaid Revenue',
    shortName: 'Mngd Medicaid',
    category: 'revenue',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'non_skilled_days',
    formatType: 'currency',
    mappingKeys: ['managed_medicaid', 'mco_medicaid', 'mngd_mcaid'],
  },
  {
    code: '4130',
    name: 'Private Pay Revenue',
    shortName: 'Private',
    category: 'revenue',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'non_skilled_days',
    formatType: 'currency',
    mappingKeys: ['private_pay', 'private_revenue', 'private'],
  },
  {
    code: '4140',
    name: 'Veterans Revenue',
    shortName: 'VA',
    category: 'revenue',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'non_skilled_days',
    formatType: 'currency',
    mappingKeys: ['va_revenue', 'veterans', 'va'],
  },
  {
    code: '4150',
    name: 'Hospice Revenue',
    shortName: 'Hospice',
    category: 'revenue',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'non_skilled_days',
    formatType: 'currency',
    mappingKeys: ['hospice_revenue', 'hospice'],
  },
  {
    code: '4199',
    name: 'Total Non-Skilled Revenue',
    shortName: 'Tot Non-Skill',
    category: 'revenue',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: true,
    parentCode: '4100',
    ppdEligible: true,
    ppdDenominator: 'non_skilled_days',
    formatType: 'currency',
  },

  // Skilled Revenue - 4200 Series
  {
    code: '4200',
    name: 'Skilled Revenue',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '4210',
    name: 'Medicare Part A Revenue',
    shortName: 'Medicare A',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['medicare_revenue', 'medicare_a', 'mcr_part_a', 'pdpm'],
  },
  {
    code: '4215',
    name: 'Medicare Advantage Revenue',
    shortName: 'Medicare Adv',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['medicare_advantage', 'ma_revenue', 'mcr_advantage'],
  },
  {
    code: '4220',
    name: 'Managed Medicaid Revenue - Skilled',
    shortName: 'Mngd Mcaid Sk',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['managed_medicaid_skilled', 'mco_skilled'],
  },
  {
    code: '4230',
    name: 'Medicaid Complex Care Revenue',
    shortName: 'Mcaid Complex',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['medicaid_complex', 'complex_care'],
  },
  {
    code: '4235',
    name: 'Medicaid Bariatric Revenue',
    shortName: 'Mcaid Bariatric',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['medicaid_bariatric', 'bariatric'],
  },
  {
    code: '4240',
    name: 'Veterans Revenue - Skilled',
    shortName: 'VA Skilled',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['va_skilled', 'veterans_skilled'],
  },
  {
    code: '4250',
    name: 'HMO/Commercial Insurance Revenue',
    shortName: 'HMO/Comm',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['hmo_revenue', 'commercial', 'insurance'],
  },
  {
    code: '4260',
    name: 'ISNP Revenue',
    shortName: 'ISNP',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['isnp_revenue', 'isnp'],
  },
  {
    code: '4299',
    name: 'Total Skilled Revenue',
    shortName: 'Tot Skilled',
    category: 'revenue',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: true,
    parentCode: '4200',
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
  },

  // Vent Revenue - 4300 Series
  {
    code: '4300',
    name: 'Vent/Trach Revenue',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '4310',
    name: 'Medicaid Revenue - Vent',
    shortName: 'Mcaid Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['medicaid_vent', 'vent_medicaid'],
  },
  {
    code: '4320',
    name: 'Managed Medicaid Revenue - Vent',
    shortName: 'Mngd Mcaid Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['managed_medicaid_vent', 'mco_vent'],
  },
  {
    code: '4330',
    name: 'Private Revenue - Vent',
    shortName: 'Private Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['private_vent'],
  },
  {
    code: '4340',
    name: 'Veterans Revenue - Vent',
    shortName: 'VA Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['va_vent', 'veterans_vent'],
  },
  {
    code: '4350',
    name: 'Hospice Revenue - Vent',
    shortName: 'Hospice Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['hospice_vent'],
  },
  {
    code: '4360',
    name: 'Medicare Revenue - Vent',
    shortName: 'Medicare Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['medicare_vent'],
  },
  {
    code: '4370',
    name: 'HMO Revenue - Vent',
    shortName: 'HMO Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['hmo_vent'],
  },
  {
    code: '4399',
    name: 'Total Vent Revenue',
    shortName: 'Tot Vent',
    category: 'revenue',
    subcategory: 'vent',
    isHeader: false,
    isTotal: true,
    parentCode: '4300',
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
  },

  // Other Revenue - 4400 Series
  {
    code: '4400',
    name: 'Other Revenue',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '4410',
    name: 'Medicare Part B Revenue',
    shortName: 'Medicare B',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['medicare_b', 'mcr_part_b', 'part_b'],
  },
  {
    code: '4415',
    name: 'Telehealth Revenue - MCR B',
    shortName: 'Telehealth',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['telehealth', 'telehealth_revenue'],
  },
  {
    code: '4420',
    name: 'Therapy - Outpatient Revenue',
    shortName: 'Outpt Therapy',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
    mappingKeys: ['outpatient_therapy', 'op_therapy'],
  },
  {
    code: '4430',
    name: 'UPL/Quality Enhancement Revenue',
    shortName: 'UPL/QE',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['upl', 'quality_enhancement', 'igp'],
  },
  {
    code: '4440',
    name: 'COVID Expense Reimbursement',
    shortName: 'COVID Reimb',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
    mappingKeys: ['covid_reimbursement', 'prf', 'provider_relief'],
  },
  {
    code: '4450',
    name: 'State/Federal COVID Grants',
    shortName: 'COVID Grants',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
    mappingKeys: ['covid_grants', 'state_covid'],
  },
  {
    code: '4460',
    name: 'Interest Income',
    shortName: 'Interest Inc',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
    mappingKeys: ['interest_income'],
  },
  {
    code: '4470',
    name: 'Miscellaneous Revenue',
    shortName: 'Misc Rev',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['misc_revenue', 'other_revenue', 'sundry'],
  },
  {
    code: '4480',
    name: 'Cafeteria/Gift Shop Revenue',
    shortName: 'Cafe/Gift',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
    mappingKeys: ['cafeteria', 'gift_shop'],
  },
  {
    code: '4499',
    name: 'Total Other Revenue',
    shortName: 'Tot Other Rev',
    category: 'revenue',
    subcategory: 'other_revenue',
    isHeader: false,
    isTotal: true,
    parentCode: '4400',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Total Revenue
  {
    code: '4999',
    name: 'Total Revenue',
    shortName: 'Total Rev',
    category: 'revenue',
    isHeader: false,
    isTotal: true,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OPERATING EXPENSES - 5000 Series
  // ═══════════════════════════════════════════════════════════════════════════

  // Ancillary - Therapy Expenses - 5100 Series
  {
    code: '5100',
    name: 'Ancillary Expenses',
    category: 'ancillary_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5110',
    name: 'Therapy Expenses',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5111',
    name: 'Therapy Wages - PT',
    shortName: 'PT Wages',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['pt_wages', 'physical_therapy_wages'],
  },
  {
    code: '5112',
    name: 'Therapy Wages - OT',
    shortName: 'OT Wages',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['ot_wages', 'occupational_therapy_wages'],
  },
  {
    code: '5113',
    name: 'Therapy Wages - SLP',
    shortName: 'SLP Wages',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['slp_wages', 'speech_therapy_wages'],
  },
  {
    code: '5114',
    name: 'Therapy Wages - Assistants (PTA/COTA)',
    shortName: 'Asst Wages',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['pta_wages', 'cota_wages', 'assistant_wages'],
  },
  {
    code: '5115',
    name: 'Therapy Benefits',
    shortName: 'Therapy Ben',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['therapy_benefits'],
  },
  {
    code: '5116',
    name: 'Therapy Contract/Agency',
    shortName: 'Therapy Contract',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['therapy_contract', 'therapy_agency', 'contract_therapy'],
  },
  {
    code: '5117',
    name: 'Therapy Supplies',
    shortName: 'Therapy Suppl',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['therapy_supplies'],
  },
  {
    code: '5118',
    name: 'Therapy Other',
    shortName: 'Therapy Other',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
    mappingKeys: ['therapy_other', 'therapy_misc'],
  },
  {
    code: '5119',
    name: 'Total Therapy Expenses',
    shortName: 'Tot Therapy',
    category: 'ancillary_expense',
    subcategory: 'therapy',
    isHeader: false,
    isTotal: true,
    parentCode: '5110',
    ppdEligible: true,
    ppdDenominator: 'skilled_days',
    formatType: 'currency',
  },

  // Non-Therapy Ancillary - 5150 Series
  {
    code: '5150',
    name: 'Non-Therapy Ancillary',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5151',
    name: 'Pharmacy Expense',
    shortName: 'Pharmacy',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['pharmacy', 'drugs', 'medications'],
  },
  {
    code: '5152',
    name: 'Lab Expense',
    shortName: 'Lab',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['lab', 'laboratory'],
  },
  {
    code: '5153',
    name: 'Radiology/X-Ray Expense',
    shortName: 'Radiology',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['radiology', 'xray', 'imaging'],
  },
  {
    code: '5154',
    name: 'Oxygen/Respiratory Supplies',
    shortName: 'O2/Resp',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['oxygen', 'respiratory', 'o2'],
  },
  {
    code: '5155',
    name: 'Medical Director Fees',
    shortName: 'Med Director',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['medical_director', 'med_director'],
  },
  {
    code: '5156',
    name: 'Physician Services',
    shortName: 'Physician Svc',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['physician_services', 'doctor_fees'],
  },
  {
    code: '5157',
    name: 'Dentist/Podiatrist/Optometry',
    shortName: 'Dental/Pod/Opt',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dental', 'podiatry', 'optometry'],
  },
  {
    code: '5158',
    name: 'Other Ancillary',
    shortName: 'Other Ancillary',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['other_ancillary'],
  },
  {
    code: '5159',
    name: 'Total Non-Therapy Ancillary',
    shortName: 'Tot Non-Ther',
    category: 'ancillary_expense',
    subcategory: 'non_therapy',
    isHeader: false,
    isTotal: true,
    parentCode: '5150',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },
  {
    code: '5199',
    name: 'Total Ancillary Expenses',
    shortName: 'Tot Ancillary',
    category: 'ancillary_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5100',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Nursing Expenses - 5200 Series
  {
    code: '5200',
    name: 'Nursing Expenses',
    category: 'nursing_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5210',
    name: 'Nursing Wages - RN',
    shortName: 'RN Wages',
    category: 'nursing_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['rn_wages', 'registered_nurse_wages'],
  },
  {
    code: '5211',
    name: 'Nursing Wages - LPN/LVN',
    shortName: 'LPN Wages',
    category: 'nursing_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['lpn_wages', 'lvn_wages'],
  },
  {
    code: '5212',
    name: 'Nursing Wages - CNA/Aide',
    shortName: 'CNA Wages',
    category: 'nursing_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['cna_wages', 'aide_wages', 'nursing_aide'],
  },
  {
    code: '5213',
    name: 'Nursing Wages - DON/ADON',
    shortName: 'DON Wages',
    category: 'nursing_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['don_wages', 'adon_wages', 'nursing_admin'],
  },
  {
    code: '5214',
    name: 'Nursing Wages - Unit Clerks/Other',
    shortName: 'Clerk Wages',
    category: 'nursing_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['unit_clerk_wages', 'nursing_clerk'],
  },
  {
    code: '5220',
    name: 'Nursing Benefits',
    shortName: 'Nursing Ben',
    category: 'nursing_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['nursing_benefits'],
  },
  {
    code: '5221',
    name: 'Nursing Payroll Taxes',
    shortName: 'Nursing PR Tax',
    category: 'nursing_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['nursing_payroll_tax'],
  },
  {
    code: '5230',
    name: 'Nursing Agency/Contract - RN',
    shortName: 'Agency RN',
    category: 'nursing_expense',
    subcategory: 'agency',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['agency_rn', 'contract_rn', 'travel_rn'],
  },
  {
    code: '5231',
    name: 'Nursing Agency/Contract - LPN',
    shortName: 'Agency LPN',
    category: 'nursing_expense',
    subcategory: 'agency',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['agency_lpn', 'contract_lpn', 'travel_lpn'],
  },
  {
    code: '5232',
    name: 'Nursing Agency/Contract - CNA',
    shortName: 'Agency CNA',
    category: 'nursing_expense',
    subcategory: 'agency',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['agency_cna', 'contract_cna', 'travel_cna'],
  },
  {
    code: '5240',
    name: 'Nursing Purchased Services/Consulting',
    shortName: 'Nurs Consulting',
    category: 'nursing_expense',
    subcategory: 'purchased_services',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['nursing_consulting', 'nursing_purchased'],
  },
  {
    code: '5250',
    name: 'Nursing Patient Supplies - Incontinent',
    shortName: 'Incont Suppl',
    category: 'nursing_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['incontinent_supplies', 'briefs', 'incontinence'],
  },
  {
    code: '5251',
    name: 'Nursing Patient Supplies - Wound Care',
    shortName: 'Wound Suppl',
    category: 'nursing_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['wound_care', 'wound_supplies'],
  },
  {
    code: '5252',
    name: 'Nursing Patient Supplies - IV/Tube Feeding',
    shortName: 'IV/Tube Suppl',
    category: 'nursing_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['iv_supplies', 'tube_feeding', 'enteral'],
  },
  {
    code: '5253',
    name: 'Nursing Patient Supplies - Other',
    shortName: 'Other Suppl',
    category: 'nursing_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['other_nursing_supplies', 'nursing_supplies_other'],
  },
  {
    code: '5260',
    name: 'Nursing Resource Fee',
    shortName: 'Resource Fee',
    category: 'nursing_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['resource_fee', 'nursing_resource'],
  },
  {
    code: '5270',
    name: 'Nursing Education/Training',
    shortName: 'Nurs Training',
    category: 'nursing_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['nursing_training', 'nursing_education'],
  },
  {
    code: '5280',
    name: 'Nursing Other',
    shortName: 'Nursing Other',
    category: 'nursing_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['nursing_other', 'nursing_misc'],
  },
  {
    code: '5299',
    name: 'Total Nursing Expenses',
    shortName: 'Tot Nursing',
    category: 'nursing_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5200',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Vent/Respiratory Expenses - 5300 Series
  {
    code: '5300',
    name: 'Vent/Respiratory Expenses',
    category: 'vent_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5310',
    name: 'Vent Wages - RN',
    shortName: 'Vent RN Wages',
    category: 'vent_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['vent_rn_wages'],
  },
  {
    code: '5311',
    name: 'Vent Wages - RT',
    shortName: 'RT Wages',
    category: 'vent_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['rt_wages', 'respiratory_therapist'],
  },
  {
    code: '5312',
    name: 'Vent Wages - Other',
    shortName: 'Vent Other Wages',
    category: 'vent_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['vent_other_wages'],
  },
  {
    code: '5320',
    name: 'Vent Benefits',
    shortName: 'Vent Benefits',
    category: 'vent_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['vent_benefits'],
  },
  {
    code: '5330',
    name: 'Vent Purchased Services/Consulting',
    shortName: 'Vent Consulting',
    category: 'vent_expense',
    subcategory: 'purchased_services',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['vent_consulting', 'vent_purchased'],
  },
  {
    code: '5340',
    name: 'Vent Patient Supplies',
    shortName: 'Vent Supplies',
    category: 'vent_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['vent_supplies', 'respiratory_supplies'],
  },
  {
    code: '5350',
    name: 'Vent Equipment Lease/Rental',
    shortName: 'Vent Equip',
    category: 'vent_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['vent_equipment', 'vent_lease'],
  },
  {
    code: '5360',
    name: 'Vent Other',
    shortName: 'Vent Other',
    category: 'vent_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
    mappingKeys: ['vent_other', 'vent_misc'],
  },
  {
    code: '5399',
    name: 'Total Vent Expenses',
    shortName: 'Tot Vent Exp',
    category: 'vent_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5300',
    ppdEligible: true,
    ppdDenominator: 'vent_days',
    formatType: 'currency',
  },

  // Plant/Maintenance Expenses - 5400 Series
  {
    code: '5400',
    name: 'Plant/Maintenance Expenses',
    category: 'plant_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5410',
    name: 'Plant Wages',
    shortName: 'Plant Wages',
    category: 'plant_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['plant_wages', 'maintenance_wages'],
  },
  {
    code: '5420',
    name: 'Plant Benefits',
    shortName: 'Plant Benefits',
    category: 'plant_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['plant_benefits'],
  },
  {
    code: '5430',
    name: 'Utilities - Electric',
    shortName: 'Electric',
    category: 'plant_expense',
    subcategory: 'utilities',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['electric', 'electricity'],
  },
  {
    code: '5431',
    name: 'Utilities - Gas',
    shortName: 'Gas',
    category: 'plant_expense',
    subcategory: 'utilities',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['gas', 'natural_gas'],
  },
  {
    code: '5432',
    name: 'Utilities - Water/Sewer',
    shortName: 'Water/Sewer',
    category: 'plant_expense',
    subcategory: 'utilities',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['water', 'sewer', 'water_sewer'],
  },
  {
    code: '5433',
    name: 'Utilities - Trash Removal',
    shortName: 'Trash',
    category: 'plant_expense',
    subcategory: 'utilities',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['trash', 'waste', 'garbage'],
  },
  {
    code: '5440',
    name: 'Minor Equipment',
    shortName: 'Minor Equip',
    category: 'plant_expense',
    subcategory: 'maintenance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['minor_equipment', 'small_equipment'],
  },
  {
    code: '5441',
    name: 'Repairs & Maintenance - Building',
    shortName: 'R&M Building',
    category: 'plant_expense',
    subcategory: 'maintenance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['building_repairs', 'building_maintenance'],
  },
  {
    code: '5442',
    name: 'Repairs & Maintenance - Equipment',
    shortName: 'R&M Equipment',
    category: 'plant_expense',
    subcategory: 'maintenance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['equipment_repairs', 'equipment_maintenance'],
  },
  {
    code: '5443',
    name: 'Repairs & Maintenance - Grounds',
    shortName: 'R&M Grounds',
    category: 'plant_expense',
    subcategory: 'maintenance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['grounds', 'landscaping', 'lawn'],
  },
  {
    code: '5450',
    name: 'Plant Contract Services',
    shortName: 'Plant Contract',
    category: 'plant_expense',
    subcategory: 'purchased_services',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['plant_contract', 'maintenance_contract'],
  },
  {
    code: '5460',
    name: 'Plant Supplies',
    shortName: 'Plant Supplies',
    category: 'plant_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['plant_supplies', 'maintenance_supplies'],
  },
  {
    code: '5470',
    name: 'Plant Other',
    shortName: 'Plant Other',
    category: 'plant_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['plant_other', 'plant_misc'],
  },
  {
    code: '5499',
    name: 'Total Plant Expenses',
    shortName: 'Tot Plant',
    category: 'plant_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5400',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Housekeeping - 5500 Series
  {
    code: '5500',
    name: 'Housekeeping Expenses',
    category: 'housekeeping_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5510',
    name: 'Housekeeping Wages',
    shortName: 'HK Wages',
    category: 'housekeeping_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['housekeeping_wages', 'hk_wages'],
  },
  {
    code: '5520',
    name: 'Housekeeping Benefits',
    shortName: 'HK Benefits',
    category: 'housekeeping_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['housekeeping_benefits', 'hk_benefits'],
  },
  {
    code: '5530',
    name: 'Housekeeping Supplies',
    shortName: 'HK Supplies',
    category: 'housekeeping_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['housekeeping_supplies', 'cleaning_supplies'],
  },
  {
    code: '5540',
    name: 'Housekeeping Contract Services',
    shortName: 'HK Contract',
    category: 'housekeeping_expense',
    subcategory: 'purchased_services',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['housekeeping_contract'],
  },
  {
    code: '5550',
    name: 'Housekeeping Other',
    shortName: 'HK Other',
    category: 'housekeeping_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['housekeeping_other'],
  },
  {
    code: '5599',
    name: 'Total Housekeeping Expenses',
    shortName: 'Tot HK',
    category: 'housekeeping_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5500',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Laundry - 5600 Series
  {
    code: '5600',
    name: 'Laundry Expenses',
    category: 'laundry_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5610',
    name: 'Laundry Wages',
    shortName: 'Laundry Wages',
    category: 'laundry_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['laundry_wages'],
  },
  {
    code: '5620',
    name: 'Laundry Benefits',
    shortName: 'Laundry Ben',
    category: 'laundry_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['laundry_benefits'],
  },
  {
    code: '5630',
    name: 'Laundry Supplies',
    shortName: 'Laundry Suppl',
    category: 'laundry_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['laundry_supplies'],
  },
  {
    code: '5640',
    name: 'Laundry Contract/Outside Services',
    shortName: 'Laundry Contract',
    category: 'laundry_expense',
    subcategory: 'purchased_services',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['laundry_contract', 'linen_service'],
  },
  {
    code: '5650',
    name: 'Laundry Other',
    shortName: 'Laundry Other',
    category: 'laundry_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['laundry_other'],
  },
  {
    code: '5699',
    name: 'Total Laundry Expenses',
    shortName: 'Tot Laundry',
    category: 'laundry_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5600',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Dietary - 5700 Series
  {
    code: '5700',
    name: 'Dietary Expenses',
    category: 'dietary_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5710',
    name: 'Dietary Wages',
    shortName: 'Dietary Wages',
    category: 'dietary_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dietary_wages', 'food_service_wages'],
  },
  {
    code: '5720',
    name: 'Dietary Benefits',
    shortName: 'Dietary Ben',
    category: 'dietary_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dietary_benefits'],
  },
  {
    code: '5730',
    name: 'Dietary Contract Services',
    shortName: 'Dietary Contract',
    category: 'dietary_expense',
    subcategory: 'purchased_services',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dietary_contract', 'food_management'],
  },
  {
    code: '5740',
    name: 'Food Cost - Raw Food',
    shortName: 'Raw Food',
    category: 'dietary_expense',
    subcategory: 'food',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['raw_food', 'food_cost', 'groceries'],
  },
  {
    code: '5741',
    name: 'Food Cost - Supplements/Thickeners',
    shortName: 'Supplements',
    category: 'dietary_expense',
    subcategory: 'food',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['supplements', 'thickeners', 'nutritional_supplements'],
  },
  {
    code: '5750',
    name: 'Dietary Supplies',
    shortName: 'Dietary Suppl',
    category: 'dietary_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dietary_supplies', 'kitchen_supplies'],
  },
  {
    code: '5760',
    name: 'Dietary Equipment',
    shortName: 'Dietary Equip',
    category: 'dietary_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dietary_equipment', 'kitchen_equipment'],
  },
  {
    code: '5770',
    name: 'Dietary Other',
    shortName: 'Dietary Other',
    category: 'dietary_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dietary_other', 'dietary_misc'],
  },
  {
    code: '5799',
    name: 'Total Dietary Expenses',
    shortName: 'Tot Dietary',
    category: 'dietary_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5700',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Social Services - 5800 Series
  {
    code: '5800',
    name: 'Social Services Expenses',
    category: 'social_services_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5810',
    name: 'Social Services Wages',
    shortName: 'SS Wages',
    category: 'social_services_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['social_services_wages', 'social_worker_wages'],
  },
  {
    code: '5820',
    name: 'Social Services Benefits',
    shortName: 'SS Benefits',
    category: 'social_services_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['social_services_benefits'],
  },
  {
    code: '5830',
    name: 'Social Services Other',
    shortName: 'SS Other',
    category: 'social_services_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['social_services_other'],
  },
  {
    code: '5899',
    name: 'Total Social Services Expenses',
    shortName: 'Tot SS',
    category: 'social_services_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5800',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Activities - 5900 Series
  {
    code: '5900',
    name: 'Activities Expenses',
    category: 'activities_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '5910',
    name: 'Activities Wages',
    shortName: 'Act Wages',
    category: 'activities_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['activities_wages'],
  },
  {
    code: '5920',
    name: 'Activities Benefits',
    shortName: 'Act Benefits',
    category: 'activities_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['activities_benefits'],
  },
  {
    code: '5930',
    name: 'Activities Supplies',
    shortName: 'Act Supplies',
    category: 'activities_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['activities_supplies'],
  },
  {
    code: '5940',
    name: 'Activities Other',
    shortName: 'Act Other',
    category: 'activities_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['activities_other'],
  },
  {
    code: '5999',
    name: 'Total Activities Expenses',
    shortName: 'Tot Activities',
    category: 'activities_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '5900',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Medical Records - 6000 Series
  {
    code: '6000',
    name: 'Medical Records Expenses',
    category: 'medical_records_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '6010',
    name: 'Medical Records Wages',
    shortName: 'MR Wages',
    category: 'medical_records_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['medical_records_wages', 'him_wages'],
  },
  {
    code: '6020',
    name: 'Medical Records Benefits',
    shortName: 'MR Benefits',
    category: 'medical_records_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['medical_records_benefits'],
  },
  {
    code: '6030',
    name: 'Medical Records Supplies',
    shortName: 'MR Supplies',
    category: 'medical_records_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['medical_records_supplies'],
  },
  {
    code: '6040',
    name: 'Medical Records Other',
    shortName: 'MR Other',
    category: 'medical_records_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['medical_records_other'],
  },
  {
    code: '6099',
    name: 'Total Medical Records Expenses',
    shortName: 'Tot MR',
    category: 'medical_records_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '6000',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Administration - 6100 Series
  {
    code: '6100',
    name: 'Administration Expenses',
    category: 'administration_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '6110',
    name: 'Admin Wages - Administrator',
    shortName: 'Admin Wages',
    category: 'administration_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['administrator_salary', 'admin_wages', 'nha_salary'],
  },
  {
    code: '6111',
    name: 'Admin Wages - Business Office',
    shortName: 'Bus Office Wages',
    category: 'administration_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['business_office_wages', 'billing_wages'],
  },
  {
    code: '6112',
    name: 'Admin Wages - Reception/Clerical',
    shortName: 'Clerical Wages',
    category: 'administration_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['reception_wages', 'clerical_wages'],
  },
  {
    code: '6113',
    name: 'Admin Wages - HR/Staffing',
    shortName: 'HR Wages',
    category: 'administration_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['hr_wages', 'staffing_wages'],
  },
  {
    code: '6114',
    name: 'Admin Wages - Marketing/Admissions',
    shortName: 'Marketing Wages',
    category: 'administration_expense',
    subcategory: 'wages',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['marketing_wages', 'admissions_wages'],
  },
  {
    code: '6120',
    name: 'Admin Benefits',
    shortName: 'Admin Benefits',
    category: 'administration_expense',
    subcategory: 'benefits',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['admin_benefits'],
  },
  {
    code: '6130',
    name: 'Admin Purchased Services/Consulting',
    shortName: 'Admin Consulting',
    category: 'administration_expense',
    subcategory: 'purchased_services',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['admin_consulting', 'consulting_fees'],
  },
  {
    code: '6140',
    name: 'IT/Computer Expense',
    shortName: 'IT Expense',
    category: 'administration_expense',
    subcategory: 'it',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['it_expense', 'computer', 'software'],
  },
  {
    code: '6141',
    name: 'EHR/EMR Software',
    shortName: 'EHR/EMR',
    category: 'administration_expense',
    subcategory: 'it',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['ehr', 'emr', 'pointclickcare', 'pcc'],
  },
  {
    code: '6150',
    name: 'Insurance - General Liability',
    shortName: 'GL Insurance',
    category: 'administration_expense',
    subcategory: 'insurance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['general_liability', 'liability_insurance'],
  },
  {
    code: '6151',
    name: 'Insurance - Professional Liability',
    shortName: 'Prof Liability',
    category: 'administration_expense',
    subcategory: 'insurance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['professional_liability', 'malpractice'],
  },
  {
    code: '6152',
    name: 'Insurance - Workers Compensation',
    shortName: 'Workers Comp',
    category: 'administration_expense',
    subcategory: 'insurance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['workers_comp', 'workerscomp'],
  },
  {
    code: '6153',
    name: 'Insurance - Property/Casualty',
    shortName: 'Prop Insurance',
    category: 'administration_expense',
    subcategory: 'insurance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['property_insurance', 'casualty_insurance'],
  },
  {
    code: '6154',
    name: 'Insurance - Other',
    shortName: 'Other Insurance',
    category: 'administration_expense',
    subcategory: 'insurance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['other_insurance'],
  },
  {
    code: '6160',
    name: 'Telecom/Communications',
    shortName: 'Telecom',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['telecom', 'phone', 'communications'],
  },
  {
    code: '6170',
    name: 'Legal Fees',
    shortName: 'Legal',
    category: 'administration_expense',
    subcategory: 'legal',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['legal_fees', 'legal', 'attorney'],
  },
  {
    code: '6171',
    name: 'Accounting/Audit Fees',
    shortName: 'Accounting',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['accounting', 'audit', 'cpa'],
  },
  {
    code: '6180',
    name: 'Recruitment/Advertising',
    shortName: 'Recruitment',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['recruitment', 'advertising', 'job_posting'],
  },
  {
    code: '6181',
    name: 'Marketing/Community Relations',
    shortName: 'Marketing',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['marketing', 'community_relations'],
  },
  {
    code: '6182',
    name: 'Travel & Entertainment',
    shortName: 'Travel',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['travel', 'entertainment', 't_and_e'],
  },
  {
    code: '6183',
    name: 'Office Supplies',
    shortName: 'Office Supplies',
    category: 'administration_expense',
    subcategory: 'supplies',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['office_supplies'],
  },
  {
    code: '6184',
    name: 'Printing/Postage',
    shortName: 'Print/Postage',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['printing', 'postage'],
  },
  {
    code: '6185',
    name: 'Dues & Subscriptions',
    shortName: 'Dues/Subs',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['dues', 'subscriptions', 'memberships'],
  },
  {
    code: '6186',
    name: 'Education & Training',
    shortName: 'Education',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['education', 'training', 'continuing_education'],
  },
  {
    code: '6187',
    name: 'Licenses & Permits',
    shortName: 'Licenses',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['licenses', 'permits', 'regulatory'],
  },
  {
    code: '6188',
    name: 'Resource Fee',
    shortName: 'Resource Fee',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['resource_fee', 'admin_resource'],
  },
  {
    code: '6190',
    name: 'Admin Other',
    shortName: 'Admin Other',
    category: 'administration_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['admin_other', 'admin_misc'],
  },
  {
    code: '6199',
    name: 'Total Administration Expenses',
    shortName: 'Tot Admin',
    category: 'administration_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '6100',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Bad Debt - 6200 Series
  {
    code: '6200',
    name: 'Bad Debt Expense',
    category: 'bad_debt',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['bad_debt', 'uncollectible', 'write_off'],
  },

  // Bed Tax - 6300 Series
  {
    code: '6300',
    name: 'Provider Tax/Bed Tax',
    category: 'bed_tax',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['bed_tax', 'provider_tax', 'quality_assessment'],
  },

  // Total Operating Expenses
  {
    code: '6499',
    name: 'Total Operating Expenses',
    shortName: 'Tot Op Exp',
    category: 'administration_expense',
    isHeader: false,
    isTotal: true,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Management Fee - 6500 Series
  {
    code: '6500',
    name: 'Management Fee',
    category: 'management_fee',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['management_fee', 'mgmt_fee'],
    description: 'Typically 4-6% of revenue',
  },

  // EBITDAR
  {
    code: '6600',
    name: 'EBITDAR',
    category: 'revenue',
    isHeader: false,
    isTotal: true,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    description: 'Revenue - Operating Expenses - Management Fee',
  },

  // Property Expenses - 7000 Series
  {
    code: '7000',
    name: 'Property Expenses',
    category: 'property_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '7010',
    name: 'Rent/Lease Expense',
    shortName: 'Rent',
    category: 'property_expense',
    subcategory: 'rent',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['rent', 'lease_expense', 'facility_lease'],
  },
  {
    code: '7020',
    name: 'Property Taxes',
    shortName: 'Prop Tax',
    category: 'property_expense',
    subcategory: 'taxes',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['property_taxes', 'real_estate_taxes'],
  },
  {
    code: '7030',
    name: 'Property Insurance',
    shortName: 'Prop Insurance',
    category: 'property_expense',
    subcategory: 'insurance',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['property_insurance'],
  },
  {
    code: '7099',
    name: 'Total Property Expenses',
    shortName: 'Tot Property',
    category: 'property_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '7000',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // EBITDA
  {
    code: '7100',
    name: 'EBITDA',
    category: 'revenue',
    isHeader: false,
    isTotal: true,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    description: 'EBITDAR - Property Expenses',
  },

  // Other Expenses - 8000 Series
  {
    code: '8000',
    name: 'Other Expenses',
    category: 'other_expense',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
  },
  {
    code: '8010',
    name: 'Depreciation',
    shortName: 'Depreciation',
    category: 'other_expense',
    subcategory: 'depreciation',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['depreciation'],
  },
  {
    code: '8020',
    name: 'Amortization',
    shortName: 'Amortization',
    category: 'other_expense',
    subcategory: 'depreciation',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['amortization'],
  },
  {
    code: '8030',
    name: 'Interest Expense',
    shortName: 'Interest',
    category: 'other_expense',
    subcategory: 'interest',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['interest_expense', 'interest'],
  },
  {
    code: '8040',
    name: 'Gain/Loss on Asset Disposal',
    shortName: 'G/L Assets',
    category: 'other_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'currency',
    mappingKeys: ['gain_loss_assets', 'asset_disposal'],
  },
  {
    code: '8050',
    name: 'Other Misc Expense',
    shortName: 'Misc Expense',
    category: 'other_expense',
    subcategory: 'other',
    isHeader: false,
    isTotal: false,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    mappingKeys: ['misc_expense', 'other_misc'],
  },
  {
    code: '8099',
    name: 'Total Other Expenses',
    shortName: 'Tot Other Exp',
    category: 'other_expense',
    isHeader: false,
    isTotal: true,
    parentCode: '8000',
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
  },

  // Net Income
  {
    code: '9000',
    name: 'Net Income',
    category: 'revenue',
    isHeader: false,
    isTotal: true,
    ppdEligible: true,
    ppdDenominator: 'total_days',
    formatType: 'currency',
    description: 'EBITDA - Other Expenses',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PATIENT DAYS - 9100 Series
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: '9100',
    name: 'Patient Days',
    category: 'patient_days',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
  },

  // Non-Skilled Days
  {
    code: '9110',
    name: 'Non-Skilled Patient Days',
    category: 'patient_days',
    subcategory: 'non_skilled',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
  },
  {
    code: '9111',
    name: 'Medicaid Days',
    shortName: 'Mcaid Days',
    category: 'patient_days',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['medicaid_days'],
  },
  {
    code: '9112',
    name: 'Managed Medicaid Days',
    shortName: 'Mngd Mcaid Days',
    category: 'patient_days',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['managed_medicaid_days', 'mco_days'],
  },
  {
    code: '9113',
    name: 'Private Pay Days',
    shortName: 'Private Days',
    category: 'patient_days',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['private_days', 'private_pay_days'],
  },
  {
    code: '9114',
    name: 'Veterans Days',
    shortName: 'VA Days',
    category: 'patient_days',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['va_days', 'veterans_days'],
  },
  {
    code: '9115',
    name: 'Hospice Days',
    shortName: 'Hospice Days',
    category: 'patient_days',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['hospice_days'],
  },
  {
    code: '9119',
    name: 'Total Non-Skilled Days',
    shortName: 'Tot NS Days',
    category: 'patient_days',
    subcategory: 'non_skilled',
    isHeader: false,
    isTotal: true,
    parentCode: '9110',
    ppdEligible: false,
    formatType: 'days',
  },

  // Skilled Days
  {
    code: '9120',
    name: 'Skilled Patient Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
  },
  {
    code: '9121',
    name: 'Medicare Part A Days',
    shortName: 'Medicare Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['medicare_days', 'mcr_days'],
  },
  {
    code: '9122',
    name: 'Medicare Advantage Days',
    shortName: 'MA Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['medicare_advantage_days', 'ma_days'],
  },
  {
    code: '9123',
    name: 'Managed Medicaid Skilled Days',
    shortName: 'Mngd Sk Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['managed_medicaid_skilled_days'],
  },
  {
    code: '9124',
    name: 'Medicaid Complex Days',
    shortName: 'Complex Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['medicaid_complex_days', 'complex_days'],
  },
  {
    code: '9125',
    name: 'Medicaid Bariatric Days',
    shortName: 'Bariatric Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['medicaid_bariatric_days', 'bariatric_days'],
  },
  {
    code: '9126',
    name: 'Veterans Skilled Days',
    shortName: 'VA Sk Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['veterans_skilled_days', 'va_skilled_days'],
  },
  {
    code: '9127',
    name: 'HMO/Commercial Days',
    shortName: 'HMO Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['hmo_days', 'commercial_days'],
  },
  {
    code: '9128',
    name: 'ISNP Days',
    shortName: 'ISNP Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['isnp_days'],
  },
  {
    code: '9129',
    name: 'Total Skilled Days',
    shortName: 'Tot Sk Days',
    category: 'patient_days',
    subcategory: 'skilled',
    isHeader: false,
    isTotal: true,
    parentCode: '9120',
    ppdEligible: false,
    formatType: 'days',
  },

  // Vent Days
  {
    code: '9130',
    name: 'Vent Patient Days',
    category: 'patient_days',
    subcategory: 'vent',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
  },
  {
    code: '9131',
    name: 'Vent Days - All Payers',
    shortName: 'Vent Days',
    category: 'patient_days',
    subcategory: 'vent',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'days',
    mappingKeys: ['vent_days', 'ventilator_days'],
  },
  {
    code: '9139',
    name: 'Total Vent Days',
    shortName: 'Tot Vent Days',
    category: 'patient_days',
    subcategory: 'vent',
    isHeader: false,
    isTotal: true,
    parentCode: '9130',
    ppdEligible: false,
    formatType: 'days',
  },

  // Total Patient Days
  {
    code: '9199',
    name: 'Total Patient Days',
    shortName: 'Tot Pat Days',
    category: 'patient_days',
    isHeader: false,
    isTotal: true,
    ppdEligible: false,
    formatType: 'days',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CENSUS/STATISTICS - 9200 Series
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: '9200',
    name: 'Census & Statistics',
    category: 'census',
    isHeader: true,
    isTotal: false,
    ppdEligible: false,
    formatType: 'number',
  },
  {
    code: '9210',
    name: 'Licensed Beds',
    shortName: 'Licensed Beds',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'number',
    mappingKeys: ['licensed_beds', 'total_beds'],
  },
  {
    code: '9211',
    name: 'Operational Beds',
    shortName: 'Op Beds',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'number',
    mappingKeys: ['operational_beds', 'staffed_beds'],
  },
  {
    code: '9220',
    name: 'Average Daily Census',
    shortName: 'ADC',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'number',
    mappingKeys: ['adc', 'average_daily_census'],
  },
  {
    code: '9230',
    name: 'Licensed Occupancy %',
    shortName: 'Lic Occ %',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'percent',
    mappingKeys: ['licensed_occupancy'],
  },
  {
    code: '9231',
    name: 'Operational Occupancy %',
    shortName: 'Op Occ %',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'percent',
    mappingKeys: ['operational_occupancy'],
  },
  {
    code: '9240',
    name: 'Skilled Mix %',
    shortName: 'Skill Mix %',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'percent',
    mappingKeys: ['skilled_mix', 'skill_mix'],
  },
  {
    code: '9241',
    name: 'Medicare Mix %',
    shortName: 'MCR Mix %',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'percent',
    mappingKeys: ['medicare_mix', 'mcr_mix'],
  },
  {
    code: '9250',
    name: 'HPPD - RN',
    shortName: 'RN HPPD',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'number',
    mappingKeys: ['rn_hppd', 'rn_hours'],
    description: 'RN Hours Per Patient Day',
  },
  {
    code: '9251',
    name: 'HPPD - Total Nursing',
    shortName: 'Total HPPD',
    category: 'census',
    isHeader: false,
    isTotal: false,
    ppdEligible: false,
    formatType: 'number',
    mappingKeys: ['total_hppd', 'nursing_hours'],
    description: 'Total Nursing Hours Per Patient Day',
  },
];

// PPD Benchmarks for common line items
export const SNF_PPD_BENCHMARKS: PPDBenchmark[] = [
  // Revenue PPD benchmarks
  { coaCode: '4110', low: 180, median: 210, high: 250, unit: 'dollars', source: 'State Medicaid Rates' },
  { coaCode: '4210', low: 450, median: 550, high: 650, unit: 'dollars', source: 'PDPM Avg' },
  { coaCode: '4999', low: 280, median: 340, high: 420, unit: 'dollars', source: 'Industry Average' },

  // Expense PPD benchmarks
  { coaCode: '5299', low: 85, median: 105, high: 130, unit: 'dollars', source: 'Industry Average' },
  { coaCode: '5119', low: 25, median: 35, high: 50, unit: 'dollars', source: 'Industry Average' },
  { coaCode: '5799', low: 18, median: 22, high: 28, unit: 'dollars', source: 'Industry Average' },
  { coaCode: '6499', low: 220, median: 260, high: 310, unit: 'dollars', source: 'Industry Average' },

  // HPPD benchmarks
  { coaCode: '9250', low: 0.5, median: 0.75, high: 1.0, unit: 'hours', source: 'CMS Requirements' },
  { coaCode: '9251', low: 3.5, median: 4.0, high: 4.5, unit: 'hours', source: 'CMS Requirements' },
];

// Helper function to get account by code
export function getAccountByCode(code: string): COAAccount | undefined {
  return SNF_CHART_OF_ACCOUNTS.find(a => a.code === code);
}

// Helper function to get all accounts in a category
export function getAccountsByCategory(category: string): COAAccount[] {
  return SNF_CHART_OF_ACCOUNTS.filter(a => a.category === category);
}

// Helper function to find account by mapping key
export function findAccountByMappingKey(key: string): COAAccount | undefined {
  const normalizedKey = key.toLowerCase().replace(/[^a-z0-9]/g, '_');
  return SNF_CHART_OF_ACCOUNTS.find(a =>
    a.mappingKeys?.some(mk => mk.toLowerCase() === normalizedKey)
  );
}

// Get child accounts for a parent
export function getChildAccounts(parentCode: string): COAAccount[] {
  return SNF_CHART_OF_ACCOUNTS.filter(a => a.parentCode === parentCode);
}

// Calculate indent level based on code structure
export function getIndentLevel(code: string): number {
  const account = getAccountByCode(code);
  if (!account) return 0;
  if (account.isHeader && !account.parentCode) return 0;
  if (account.isHeader) return 1;
  if (account.isTotal && !account.parentCode) return 0;
  if (account.isTotal) return 1;
  return account.parentCode ? 2 : 1;
}
