import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/db';
import { deals, investmentMemos } from '@/db/schema';
import { eq } from 'drizzle-orm';
import jsPDF from 'jspdf';

type RouteContext = { params: Promise<{ id: string }> };

function isValidUUID(str: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);
}

// ── GET: Export memo as PDF or DOCX ─────────────────────────────────
export async function GET(request: NextRequest, context: RouteContext) {
  try {
    const { id: dealId } = await context.params;
    if (!isValidUUID(dealId)) {
      return NextResponse.json({ error: 'Invalid deal ID' }, { status: 400 });
    }

    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') || 'pdf';

    // Load deal and memo
    const [deal] = await db.select().from(deals).where(eq(deals.id, dealId));
    if (!deal) {
      return NextResponse.json({ error: 'Deal not found' }, { status: 404 });
    }

    const [memo] = await db
      .select()
      .from(investmentMemos)
      .where(eq(investmentMemos.dealId, dealId))
      .limit(1);

    if (!memo) {
      return NextResponse.json({ error: 'Memo not generated yet' }, { status: 404 });
    }

    if (format === 'pdf') {
      const pdfBuffer = generateMemoPDF(deal, memo);

      // Update export metadata
      await db
        .update(investmentMemos)
        .set({
          lastExportedAt: new Date(),
          exportFormat: 'pdf',
        })
        .where(eq(investmentMemos.id, memo.id));

      return new NextResponse(pdfBuffer as unknown as BodyInit, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="investment-memo-${deal.name || 'deal'}.pdf"`,
        },
      });
    }

    // DOCX fallback — return formatted text
    if (format === 'docx') {
      const textContent = generateMemoText(deal, memo);

      await db
        .update(investmentMemos)
        .set({
          lastExportedAt: new Date(),
          exportFormat: 'docx',
        })
        .where(eq(investmentMemos.id, memo.id));

      return new NextResponse(textContent, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="investment-memo-${deal.name || 'deal'}.docx"`,
        },
      });
    }

    return NextResponse.json({ error: 'Unsupported format' }, { status: 400 });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Failed to export memo' }, { status: 500 });
  }
}

// ── PDF Generator ───────────────────────────────────────────────────

function generateMemoPDF(
  deal: typeof deals.$inferSelect,
  memo: typeof investmentMemos.$inferSelect
): Buffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;

  // Colors
  const primary = [20, 184, 166] as const;
  const dark = [30, 30, 30] as const;
  const gray = [100, 100, 100] as const;

  // ── Cover Page ────────────────────────────────────────────────────

  // Header bar
  doc.setFillColor(primary[0], primary[1], primary[2]);
  doc.rect(0, 0, pageWidth, 60, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('CASCADIA HEALTHCARE', margin, 20);

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Investment Memorandum', margin, 38);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(deal.name || 'Deal Analysis', margin, 50);

  // Deal info section
  doc.setTextColor(dark[0], dark[1], dark[2]);
  let y = 80;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Deal Overview', margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(gray[0], gray[1], gray[2]);

  const infoItems = [
    `Asset Type: ${deal.assetType?.toUpperCase() || 'N/A'}`,
    `State: ${deal.primaryState || 'N/A'}`,
    `Beds: ${deal.beds || 'N/A'}`,
    `Asking Price: ${deal.askingPrice ? `$${(parseFloat(deal.askingPrice) / 1e6).toFixed(1)}M` : 'N/A'}`,
    `Status: ${memo.status || 'Draft'}`,
    `Generated: ${memo.generatedAt ? new Date(memo.generatedAt).toLocaleDateString() : 'N/A'}`,
  ];

  for (const item of infoItems) {
    doc.text(item, margin, y);
    y += 6;
  }

  // Confidentiality notice
  y = 250;
  doc.setFontSize(7);
  doc.setTextColor(gray[0], gray[1], gray[2]);
  doc.text('CONFIDENTIAL — For internal use only. Not for distribution.', margin, y);
  doc.text(`Generated by SNFalyze AI Platform — ${new Date().toLocaleDateString()}`, margin, y + 5);

  // ── Content Pages ─────────────────────────────────────────────────

  const sections = [
    { title: '1. Executive Summary', content: memo.executiveSummary },
    { title: '2. Facility Overview', content: memo.facilityOverview },
    { title: '3. Market Analysis', content: memo.marketAnalysis },
    { title: '4. Financial Analysis', content: memo.financialAnalysis },
    { title: '5. Operational Assessment', content: memo.operationalAssessment },
    { title: '6. Risk Assessment', content: memo.riskAssessment },
    { title: '7. Investment Thesis', content: memo.investmentThesis },
    { title: '8. Recommendation', content: memo.recommendation },
  ];

  for (const section of sections) {
    if (!section.content) continue;

    doc.addPage();
    y = 20;

    // Section header
    doc.setFillColor(primary[0], primary[1], primary[2]);
    doc.rect(0, 0, pageWidth, 16, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, 11);

    y = 28;

    // Section content
    doc.setTextColor(dark[0], dark[1], dark[2]);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    const lines = doc.splitTextToSize(section.content, contentWidth);
    for (const line of lines) {
      if (y > 275) {
        doc.addPage();
        y = 20;
        // Mini header on continuation pages
        doc.setFillColor(primary[0], primary[1], primary[2]);
        doc.rect(0, 0, pageWidth, 8, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(7);
        doc.text(`${section.title} (continued)`, margin, 5.5);
        doc.setTextColor(dark[0], dark[1], dark[2]);
        doc.setFontSize(9);
        y = 16;
      }
      doc.text(line, margin, y);
      y += 4.5;
    }
  }

  // Due diligence checklist
  if (memo.dueDiligenceChecklist) {
    doc.addPage();
    y = 20;
    doc.setFillColor(primary[0], primary[1], primary[2]);
    doc.rect(0, 0, pageWidth, 16, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Due Diligence Checklist', margin, 11);

    y = 28;
    doc.setTextColor(dark[0], dark[1], dark[2]);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    const checklistContent = typeof memo.dueDiligenceChecklist === 'object'
      ? (memo.dueDiligenceChecklist as Record<string, string>).content || JSON.stringify(memo.dueDiligenceChecklist, null, 2)
      : String(memo.dueDiligenceChecklist);

    const checklistLines = doc.splitTextToSize(checklistContent, contentWidth);
    for (const line of checklistLines) {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += 4.5;
    }
  }

  return Buffer.from(doc.output('arraybuffer'));
}

// ── Text export (DOCX placeholder) ──────────────────────────────────

function generateMemoText(
  deal: typeof deals.$inferSelect,
  memo: typeof investmentMemos.$inferSelect
): string {
  const sections = [
    { title: 'EXECUTIVE SUMMARY', content: memo.executiveSummary },
    { title: 'FACILITY OVERVIEW', content: memo.facilityOverview },
    { title: 'MARKET ANALYSIS', content: memo.marketAnalysis },
    { title: 'FINANCIAL ANALYSIS', content: memo.financialAnalysis },
    { title: 'OPERATIONAL ASSESSMENT', content: memo.operationalAssessment },
    { title: 'RISK ASSESSMENT', content: memo.riskAssessment },
    { title: 'INVESTMENT THESIS', content: memo.investmentThesis },
    { title: 'RECOMMENDATION', content: memo.recommendation },
  ];

  let text = `INVESTMENT MEMORANDUM\n${deal.name || 'Deal Analysis'}\n${'='.repeat(60)}\n\n`;

  for (const section of sections) {
    if (!section.content) continue;
    text += `\n${section.title}\n${'-'.repeat(section.title.length)}\n\n${section.content}\n\n`;
  }

  if (memo.dueDiligenceChecklist) {
    text += `\nDUE DILIGENCE CHECKLIST\n${'='.repeat(25)}\n\n`;
    const content = typeof memo.dueDiligenceChecklist === 'object'
      ? (memo.dueDiligenceChecklist as Record<string, string>).content || JSON.stringify(memo.dueDiligenceChecklist, null, 2)
      : String(memo.dueDiligenceChecklist);
    text += content;
  }

  text += `\n\n${'='.repeat(60)}\nGenerated by SNFalyze AI Platform — ${new Date().toLocaleDateString()}\nCONFIDENTIAL — For internal use only.`;

  return text;
}
